name: Ragas Evaluation CI

on:
  push:
    branches:
      - dev

jobs:
  rag-eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas datasets ragas langchain-mistralai langchain-huggingface huggingface_hub

      - name: Run Pytest (Unit Tests)
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          HUGGING_API_KEY: ${{ secrets.HUGGING_API_KEY }}
        run: pytest tests/api_test.py

      - name: Run Ragas Evaluation
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          HUGGING_API_KEY: ${{ secrets.HUGGING_API_KEY }}
        run: python tests/evaluate_rag.py 